function hol_constr = genHolonomicConstraint(domain,frame,stance,side)
name = [side,stance];
p_foot = getCartesianPosition(domain,frame);
hol_foot_SymFun = [...
    p_foot(1);...
    p_foot(2);...
    p_foot(3)];
hol_constr = HolonomicConstraint(domain,hol_foot_SymFun,name,...
    'ConstrLabel',{{[name,'X'],[name,'Y'],[name,'Z']}},...
    'DerivativeOrder',2);
end