function ground_reaction_force(nlp, bounds)

    domain = nlp.Plant;
    x = domain.States.x;
    
    force = SymVariable('f',[1,1]);
    GRF = force;
    GRF_func = SymFunction(['GroundReactionForce',domain.Name],GRF,force);

    GRF_cstr = NlpFunction('Name',GRF_func.Name,...
        'Dimension',1,...
        'lb', bounds.constrBounds.GRF.lb,...
        'ub', bounds.constrBounds.GRF.ub,...
        'Type', 'Linear',...
        'SymFun', GRF_func,...
        'DepVariables',nlp.OptVarTable.);
end

