function [dalphaB,ddalphaB] = Func_alphaB_VA(in1,la)
%FUNC_ALPHAB_VA
%    [DALPHAB,DDALPHAB] = FUNC_ALPHAB_VA(IN1,LA)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    25-Jul-2019 16:11:37

alphaB = in1(4,:);
dalphaB = in1(9,:);
ddphi = in1(13,:);
ddx = in1(11,:);
ddy = in1(12,:);
dphi = in1(8,:);
dx = in1(6,:);
dy = in1(7,:);
phi = in1(3,:);
y = in1(2,:);
t2 = cos(alphaB);
t3 = sin(phi);
t4 = alphaB+phi;
t5 = alphaB.*2.0;
t6 = alphaB.*3.0;
t7 = dalphaB.^2;
t8 = dphi.^2;
t9 = phi.*2.0;
t10 = phi.*3.0;
t11 = cos(t4);
t12 = sin(t4);
t13 = phi+t4;
t16 = t4.*2.0;
dalphaB = -(dx+dphi.*y.*2.0+dx.*cos(t16)+dy.*sin(t16)-dphi.*la.*t3-dphi.*la.*sin(alphaB+t4))./(y.*2.0-la.*t3.*2.0);
if nargout > 1
    t18 = t4.*3.0;
    t14 = sin(t13);
    t15 = cos(t13);
    t17 = alphaB+t16;
    ddalphaB = -(ddx.*t11.*3.0+ddy.*t12+ddx.*cos(t18)+ddy.*sin(t18)+la.*t8.*cos(t17)-ddphi.*la.*sin(t17)+dalphaB.*dy.*t11.*8.0+dphi.*dy.*t11.*8.0-ddphi.*la.*t14+ddphi.*t11.*y.*4.0-la.*t2.*t7.*4.0-la.*t2.*t8.*6.0+la.*t7.*t15.*4.0+la.*t8.*t15+t7.*t12.*y.*8.0+t8.*t12.*y.*8.0-dalphaB.*dphi.*la.*t2.*1.2e+1+dalphaB.*dphi.*la.*t15.*4.0+dalphaB.*dphi.*t12.*y.*1.6e+1)./(la.*t14.*-2.0+t11.*y.*4.0+la.*sin(alphaB).*2.0);
end
