function ContactFrame = LeftFrontFoot(obj)
left_front_foot_frame = obj.Joints(getJointIndices(obj, 'knee_front_leftL_link'));
ContactFrame = CoordinateFrame(...
    'Name','LeftFrontFoot',...
    'Reference',left_front_foot_frame,...
    'Offset',[0,0,0.4],...
    'R',[0,0,0],...
    'Type','PointContactWithFriction'...
    );
end