function ContactFrame = LeftBackFoot(obj)
left_back_foot_frame = obj.Joints(getJointIndices(obj, 'knee_back_leftL_link'));
ContactFrame = CoordinateFrame(...
    'Name','LeftBackFoot',...
    'Reference',left_back_foot_frame,...
    'Offset',[0,0,0.24],...
    'R',[0,0,0],...
    'Type','PointContactWithFriction'...
    );
end