function ContactFrame = RightFrontFoot(obj)
right_front_foot_frame = obj.Joints(getJointIndices(obj, 'knee_front_rightR_link'));
ContactFrame = CoordinateFrame(...
    'Name','RightFrontFoot',...
    'Reference',right_front_foot_frame,...
    'Offset',[0,0,0.24],...
    'R',[0,0,0],...
    'Type','PointContactWithFriction'...
    );
end