function ContactFrame = RightBackFoot(obj)
right_back_foot_frame = obj.Joints(getJointIndices(obj, 'knee_back_rightR_link'));
ContactFrame = CoordinateFrame(...
    'Name','RightBackFoot',...
    'Reference',right_back_foot_frame,...
    'Offset',[0,0,0.2315],...
    'R',[0,0,0],...
    'Type','PointContactWithFriction'...
    );
end